const testEnrollees = [
    {
        firstName: "John",
        lastName: "Smith",
        email: "john.smith@test.com",
        phone: "555-0101",
        address: "123 Main St",
        city: "Seattle",
        state: "WA",
        zipCode: "98101",
        country: "US",
        package: "ELITE",
    },
    {
        firstName: "Maria",
        lastName: "Garcia",
        email: "maria.garcia@test.com",
        phone: "555-0102",
        address: "456 Pine Ave",
        city: "Los Angeles",
        state: "CA",
        zipCode: "90001",
        country: "US",
        package: "PRO",
    },
    {
        firstName: "David",
        lastName: "Johnson",
        email: "david.johnson@test.com",
        phone: "555-0103",
        address: "789 Oak Rd",
        city: "Dallas",
        state: "TX",
        zipCode: "75001",
        country: "US",
        package: "STARTER",
    },
    {
        firstName: "Sarah",
        lastName: "Wilson",
        email: "sarah.wilson@test.com",
        phone: "555-0104",
        address: "321 Elm St",
        city: "Miami",
        state: "FL",
        zipCode: "33101",
        country: "US",
        package: "ELITE",
    },
    {
        firstName: "Michael",
        lastName: "Brown",
        email: "michael.brown@test.com",
        phone: "555-0105",
        address: "654 Maple Dr",
        city: "Chicago",
        state: "IL",
        zipCode: "60601",
        country: "US",
        package: "PRO",
    },
    {
        firstName: "Jennifer",
        lastName: "Davis",
        email: "jennifer.davis@test.com",
        phone: "555-0106",
        address: "987 Cedar Ln",
        city: "Boston",
        state: "MA",
        zipCode: "02101",
        country: "US",
        package: "STARTER",
    },
    {
        firstName: "Robert",
        lastName: "Miller",
        email: "robert.miller@test.com",
        phone: "555-0107",
        address: "741 Birch Rd",
        city: "Phoenix",
        state: "AZ",
        zipCode: "85001",
        country: "US",
        package: "ELITE",
    },
    {
        firstName: "Lisa",
        lastName: "Anderson",
        email: "lisa.anderson@test.com",
        phone: "555-0108",
        address: "852 Spruce St",
        city: "Denver",
        state: "CO",
        zipCode: "80201",
        country: "US",
        package: "PRO",
    },
    {
        firstName: "James",
        lastName: "Taylor",
        email: "james.taylor@test.com",
        phone: "555-0109",
        address: "963 Pine St",
        city: "Atlanta",
        state: "GA",
        zipCode: "30301",
        country: "US",
        package: "STARTER",
    },
    {
        firstName: "Patricia",
        lastName: "Thomas",
        email: "patricia.thomas@test.com",
        phone: "555-0110",
        address: "159 Oak Ave",
        city: "Houston",
        state: "TX",
        zipCode: "77001",
        country: "US",
        package: "ELITE",
    },
    {
        firstName: "Richard",
        lastName: "Moore",
        email: "richard.moore@test.com",
        phone: "555-0111",
        address: "357 Elm Dr",
        city: "San Francisco",
        state: "CA",
        zipCode: "94101",
        country: "US",
        package: "PRO",
    },
    {
        firstName: "Linda",
        lastName: "Jackson",
        email: "linda.jackson@test.com",
        phone: "555-0112",
        address: "246 Maple St",
        city: "Las Vegas",
        state: "NV",
        zipCode: "89101",
        country: "US",
        package: "STARTER",
    },
    {
        firstName: "William",
        lastName: "White",
        email: "william.white@test.com",
        phone: "555-0113",
        address: "135 Cedar Ave",
        city: "Portland",
        state: "OR",
        zipCode: "97201",
        country: "US",
        package: "ELITE",
    },
    {
        firstName: "Elizabeth",
        lastName: "Harris",
        email: "elizabeth.harris@test.com",
        phone: "555-0114",
        address: "468 Birch St",
        city: "Nashville",
        state: "TN",
        zipCode: "37201",
        country: "US",
        package: "PRO",
    },
    {
        firstName: "Daniel",
        lastName: "Martin",
        email: "daniel.martin@test.com",
        phone: "555-0115",
        address: "791 Spruce Dr",
        city: "Austin",
        state: "TX",
        zipCode: "73301",
        country: "US",
        package: "STARTER",
    },
    {
        firstName: "Barbara",
        lastName: "Thompson",
        email: "barbara.thompson@test.com",
        phone: "555-0116",
        address: "147 Pine Ln",
        city: "San Diego",
        state: "CA",
        zipCode: "92101",
        country: "US",
        package: "ELITE",
    },
    {
        firstName: "Joseph",
        lastName: "Garcia",
        email: "joseph.garcia@test.com",
        phone: "555-0117",
        address: "258 Oak St",
        city: "Philadelphia",
        state: "PA",
        zipCode: "19101",
        country: "US",
        package: "PRO",
    },
    {
        firstName: "Margaret",
        lastName: "Martinez",
        email: "margaret.martinez@test.com",
        phone: "555-0118",
        address: "369 Elm Ave",
        city: "Detroit",
        state: "MI",
        zipCode: "48201",
        country: "US",
        package: "STARTER",
    },
    {
        firstName: "Thomas",
        lastName: "Robinson",
        email: "thomas.robinson@test.com",
        phone: "555-0119",
        address: "753 Maple Ln",
        city: "Charlotte",
        state: "NC",
        zipCode: "28201",
        country: "US",
        package: "ELITE",
    },
    {
        firstName: "Sandra",
        lastName: "Clark",
        email: "sandra.clark@test.com",
        phone: "555-0120",
        address: "951 Cedar Dr",
        city: "Indianapolis",
        state: "IN",
        zipCode: "46201",
        country: "US",
        package: "PRO",
    }
];

module.exports = testEnrollees; 